### ISSUE TITLE
smaller terminal sizes cause very odd behavior

### ISSUE THREAD

**Issue by ralsei** [Retrospring/nsc#1]
image probably speaks for itself here

![scrot116](https://cloud.githubusercontent.com/assets/16062051/13028064/95b84964-d231-11e5-9168-628d2036df4b.png)

**Comment by ghost** [comment]
thats a bug with `inquirer.rb`, which in itself is ported from `inquirer.js`. cant do anything about that

**Comment by ghost** [comment]
_maybe consider using a larger terminal_
